# Generated by Django 2.2.4 on 2020-05-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
