# Generated by Django 2.2.4 on 2020-06-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_current_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='part',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='part',
            new_name='name',
        ),
    ]
