export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_REFRESH = "AUTH_REFRESH";

export const CART_START = "CART_START";
export const CART_SUCCESS = "CART_SUCCESS";
export const CART_FAIL = "CART_FAIL";

export const FINGERPRINT_START = "FINGERPRINT_START";
export const FINGERPRINT_SUCCESS = "FINGERPRINT_SUCCESS";
export const FINGERPRINT_FAIL = "FINGERPRINT_FAIL";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADD_QUANTITY = "ADD_QUANTITY";
export const SUB_QUANTITY = "SUB_QUANTITY";
export const EMPTY_CART = "EMPTY_CART";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";
export const CHECK_QUANTITY = "CHECK_QUANTITY";

export const SET_SHIPPING_OPTIONS = "SET_SHIPPING_OPTIONS";
export const CLEAR_SHIPPING_OPTIONS = "CLEAR_SHIPPING_OPTIONS";

export const SET_BILLING_OPTIONS = "SET_BILLING_OPTIONS";
export const CLEAR_BILLING_OPTIONS = "CLEAR_BILLING_OPTIONS";
