from django.urls import path
from .views import (
    UserIDView,
    ItemListView,
    ItemDetailView,
    AddToCartView,
    OrderDetailView,
    OrderQuantityUpdateView,
    PaymentView,
    AddCouponView,
    CountryListView,
    AddressListView,
    AddressCreateView,
    AddressUpdateView,
    AddressDeleteView,
    OrderItemDeleteView,
    PaymentListView,
    PartView,
    PartTypeFilterView,
    PartCategoryFilterView,
    PartFilterView,
    PartsFiltersView,
    ItemImageView,
    ItemFilterView,
    AddToCartSessionView,
    CheckIfQuantityExistView,
    PayForOrderView
)


# app_name='api'

urlpatterns = [
    path('user-id/', UserIDView.as_view(), name='user-id'),
    path('countries/', CountryListView.as_view(), name='country-list'),
    path('addresses/', AddressListView.as_view(), name='address-list'),
    path('addresses/create/', AddressCreateView.as_view(), name='address-create'),
    path('addresses/<pk>/update/',
         AddressUpdateView.as_view(), name='address-update'),
    path('addresses/<pk>/delete/',
         AddressDeleteView.as_view(), name='address-delete'),
    path('products/', ItemListView.as_view(), name='product-list'),
    path('products/<pk>/', ItemDetailView.as_view(), name='product-detail'),
    path('add-to-cart/', AddToCartView.as_view(), name='add-to-cart'),
    path('order-summary/', OrderDetailView.as_view(), name='order-summary'),
    path('checkout/', PaymentView.as_view(), name='checkout'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('order-items/<pk>/delete/',
         OrderItemDeleteView.as_view(), name='order-item-delete'),
    path('order-item/update-quantity/',
         OrderQuantityUpdateView.as_view(), name='order-item-update-quantity'),
    path('payments/', PaymentListView.as_view(), name='payment-list'),
    path('part-filters/', PartView.as_view(), name='part-filter-list'),
    path('part-type-filter/', PartTypeFilterView.as_view(), name='part-type-filter'),
    path('part-category-filter/', PartCategoryFilterView.as_view(),
         name='part-category-filter'),
    path('part-filter/', PartFilterView.as_view(), name='part-filter'),
    path('parts-filter/', PartsFiltersView.as_view(), name='parts-filter'),
    path('image/', ItemImageView.as_view(), name='image'),
    path('item-filter-list/', ItemFilterView.as_view(), name='item-filter-list'),
    path('add-to-cart-session/', AddToCartSessionView.as_view(),
         name='add-to-cart-session'),
    path('check-if-quantity-exist/', CheckIfQuantityExistView.as_view(),
         name='check-if-quantity-exist'),
    path('pay-for-order/', PayForOrderView.as_view(),
         name='pay-for-order'),

]
